[pytest]
minversion=6.0
addopts = --cov=app --cov-report=term-missing --cov-report=html
testpaths=
    tests
python_files=
     test_*.py
      *test.py
python_functions=
      test_*
pythonpath=app
[run]
omit=
  app/schemas/*
  app/models/*
  app/config/*
  app/custom_errors/*
  app/db/*